"""The FWI gradient has the wrong SIGN in cells containing a source.

Not a DFT problem: it is present in **both** `back_prop_type` 1 and 2, so it
lives in the shared adjoint-state gradient rather than in either accumulation
scheme. Reproduced here on the plainest possible case -- 2D elastic, a single
pressure source, a homogeneous starting model, and a d(J)/d(vp) probe.

Method
------
Project the adjoint gradient onto small Gaussian patches and compare each
projection against a central finite difference of the same J. If the gradient
is right, `FD/<g,v>` is ONE constant for every patch -- the constant being
whatever scaling the engine applies to the adjoint source. Patches on the
source are compared against patches in the interior.

Two methodological points, both of which change the answer if you skip them:

* **Use a dense frequency set for back_prop_type=2.** A DFT gradient over a few
  frequencies is the gradient of a frequency-*restricted* objective and does
  not match a broadband J (test_dft_gradient.py:666-668 says the same). With
  three frequencies the interior ratios spread by 6x and the result is
  uninterpretable; with the full band they agree to ~10%.

* **Check that FD is converged.** At the source the ratio moves by 15x between
  dv=10 and dv=160 m/s, so a single large step measures nothing. At dv<=5 m/s
  it is stable to ~1%, and that is the number to trust.

Measured (60x60 grid, source at (21,30), `SEISCL_BIN=build-cuda`)
----------------------------------------------------------------
    back_prop_type=2, 128 frequency bins       back_prop_type=1
      interior  +1.97e6 +1.96e6 +1.78e6          +9.74e-9 +9.65e-9 +8.14e-9
      SOURCE    -3.60e6                          -1.64e-8
      near-src  -3.01e5   (3 cells away)         +3.98e-7

Both methods: interior consistent, source opposite in sign and ~2x in
magnitude. The contamination extends ~3-4 cells, which is why a 4-cell mute
makes the gradient usable (test_dft_inversion.py).

Hypotheses tested and REJECTED
------------------------------
1. *Band-limiting of the DFT gradient.* Using all 128 bins instead of 3 tightens
   the interior to ~10% but leaves the source sign flipped.
2. *Unconverged finite differences.* Ratios are stable to ~1% over a 20x range
   of dv at every probe including the source.
3. *savefreqs sampled before the source injection.* The forward loop calls
   savefreqs then injects; the adjoint loop injects, updates, then calls
   savefreqs (time_stepping.c). Moving the forward call after the injection and
   rebuilding changed the source ratio from -3.60e6 to -2.84e6 -- still
   negative, so this ordering is not the cause. Reverted.
4. *A material-dependent source term* (the `- s` of the adjoint-state gradient,
   thesis eq. 3.36). `src_type=100` is generated by automatic_kernels.c:592-616
   as a pressure source adding `amp/n2ave` to sxx and szz with no material
   scaling, so d(s)/d(vp) = 0 here. (Force sources DO divide by `rip`, so they
   may have an additional, separate problem -- untested.)

Still open. Note that near-source gradient contamination is normal in FWI and
is routinely muted; what is not normal is the sign being wrong, which is what
this script establishes.

Run:  SEISCL_BIN=<build> python probe_near_source_gradient.py
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gradient_common as gc                                    # noqa: E402


def setup():
    wd = gc.workdir("nearsrc")
    s = gc.make_seiscl(wd)
    start = gc.homogeneous(s)
    s.set_forward(s.src_pos_all[3, :], gc.with_anomaly(s), withgrad=False)
    s.execute()
    dobs = s.read_data()
    s.write_data({"p": dobs[0]}, filename="SeisCL_din.mat")
    return (wd, os.path.join(s.workdir, "SeisCL_din.mat"),
            [np.asarray(a, dtype=np.float64) for a in dobs], start)


def misfit(wd, din, dobs, params):
    s = gc.make_seiscl(wd, seisout=2)
    s.file_din = din
    s.set_forward(s.src_pos_all[3, :], params, withgrad=False)
    s.execute()
    return s.misfit(s.read_data(), dobs=dobs)[0]


def grad_dft(wd, din, dobs, params):
    """back_prop_type=2. ONE execute(), and set_backward() must precede it:
    with inputres=1 an earlier execute() demands a residuals file that does not
    exist yet. The DFT path re-runs the forward internally."""
    s0 = gc.make_seiscl(wd)
    nt = int(s0.NT)
    freqs = (1.0 / (nt * s0.dt)) * np.arange(1, nt // 2 + 1)

    s = gc.make_seiscl(wd, seisout=2)
    s.set_forward(s.src_pos_all[3, :], params, withgrad=False)
    s.execute()
    _, res = s.misfit(s.read_data(), dobs=dobs)

    g = gc.make_seiscl(wd, gradout=1, back_prop_type=2, inputres=1,
                       gradfreqs=freqs)
    g.file_din = din
    g.set_forward(g.src_pos_all[3, :], params, withgrad=True)
    g.set_backward(residuals=res)
    g.execute()
    return np.asarray(g.read_grad()[0], dtype=np.float64)


def grad_bnd(wd, din, dobs, params):
    """back_prop_type=1, engine-internal residuals in a single call.

    inputres=1 here would need the two-call checkpoint protocol whose first
    call must have gradout=0 (time_stepping.c:920). Not needed: the engine's
    adjoint source is proportional to (dobs - dmod), so the ratio changes by a
    constant and the signs stay comparable.
    """
    g = gc.make_seiscl(wd, gradout=1, back_prop_type=1)
    g.file_din = din
    g.set_forward(g.src_pos_all[3, :], params, withgrad=True)
    g.execute()
    return np.asarray(g.read_grad()[0], dtype=np.float64)


def probe(wd, din, dobs, start, G, steps=(1.0, 5.0)):
    zz, xx = np.indices(G.shape)
    zsrc, xsrc = 21, G.shape[1] // 2
    out = {}
    print("    max|g| at %s" % (np.unravel_index(np.abs(G).argmax(), G.shape),))
    print("    %-9s %5s %5s  %-12s  FD/<g,v> at dv = %s m/s"
          % ("region", "z", "x", "<g,v>", "/".join("%g" % d for d in steps)))
    for tag, z, x in [("SOURCE", zsrc, xsrc), ("near-src", zsrc, xsrc + 3),
                      ("interior", 28, xsrc), ("interior", 32, xsrc),
                      ("interior", 36, xsrc)]:
        v = np.exp(-((zz - z)**2 + (xx - x)**2) / (2 * 1.5**2))
        v /= v.max()
        gv = float((G * v).sum())
        ratios = []
        for dv in steps:
            pp = {k: np.array(a) for k, a in start.items()}
            pm = {k: np.array(a) for k, a in start.items()}
            pp["vp"] = pp["vp"] + dv * v
            pm["vp"] = pm["vp"] - dv * v
            fd = (misfit(wd, din, dobs, pp) - misfit(wd, din, dobs, pm))/(2*dv)
            ratios.append(fd / gv)
        out.setdefault(tag, []).append(ratios[0])
        print("    %-9s %5d %5d  %+.4e  %s"
              % (tag, z, x, gv, "  ".join("%+.4e" % r for r in ratios)))
    return out


def main():
    wd, din, dobs, start = setup()
    for name, fn in (("back_prop_type=2 (DFT, all frequency bins)", grad_dft),
                     ("back_prop_type=1 (boundary storage, time domain)",
                      grad_bnd)):
        print("\n== %s" % name)
        r = probe(wd, din, dobs, start, fn(wd, din, dobs, start))
        interior = np.array(r["interior"])
        src = r["SOURCE"][0]
        print("    interior mean %+.4e (spread %.2f) | source %+.4e -> %s"
              % (interior.mean(), interior.max()/interior.min(), src,
                 "SIGN OPPOSITE -- defect" if src*interior.mean() < 0
                 else "same sign"))


if __name__ == "__main__":
    main()
